platform :ios, '9.0'
use_frameworks!

target 'YelpForBathrooms' do
  pod 'SwiftyJSON', '~> 2.3'
  pod 'GoogleSignIn', '~> 2.4.0'
  pod 'GoogleMaps', '~> 1.10.0'
  pod 'SwiftHTTP', '~> 1.0.2'
  pod 'Alamofire', '~> 3.0'
end